# Generated by Django 4.2.7 on 2025-05-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mediCore", "0002_alter_birth_date_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archive",
            options={"verbose_name": "专病档案", "verbose_name_plural": "专病档案"},
        ),
        migrations.AlterModelOptions(
            name="archivecase",
            options={"verbose_name": "档案病例关联", "verbose_name_plural": "档案与病例关联表"},
        ),
        migrations.AlterModelOptions(
            name="case", options={"verbose_name": "病例", "verbose_name_plural": "病例表"},
        ),
        migrations.AlterModelOptions(
            name="datatable",
            options={"verbose_name": "数据", "verbose_name_plural": "数据表"},
        ),
        migrations.AlterModelOptions(
            name="datatemplate",
            options={
                "ordering": ["template_code"],
                "verbose_name": "数据模板",
                "verbose_name_plural": "数据模板",
            },
        ),
        migrations.AlterModelOptions(
            name="datatemplatecategory",
            options={"verbose_name": "数据模板分类", "verbose_name_plural": "数据模板分类表"},
        ),
        migrations.AlterModelOptions(
            name="datatemplatedictionary",
            options={"verbose_name": "模板词条关系", "verbose_name_plural": "模板词条关系"},
        ),
        migrations.AlterModelOptions(
            name="dictionary",
            options={"verbose_name": "系统词条", "verbose_name_plural": "系统词条表"},
        ),
        migrations.AlterModelOptions(
            name="identity",
            options={"verbose_name": "患者身份", "verbose_name_plural": "患者表"},
        ),
        migrations.AlterModelOptions(
            name="images", options={"verbose_name": "图片", "verbose_name_plural": "图片表"},
        ),
        migrations.RemoveIndex(model_name="dictionary", name="name_index",),
        migrations.RemoveField(model_name="archive", name="cases",),
        migrations.AddField(
            model_name="case",
            name="archives",
            field=models.ManyToManyField(
                related_name="cases",
                through="mediCore.ArchiveCase",
                to="mediCore.archive",
            ),
        ),
        migrations.AddField(
            model_name="datatemplate",
            name="dictionaries",
            field=models.ManyToManyField(
                related_name="data_templates",
                through="mediCore.DataTemplateDictionary",
                to="mediCore.dictionary",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="archive_code",
            field=models.CharField(help_text="档案编号", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="archive_description",
            field=models.TextField(blank=True, help_text="档案描述", null=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="archive_name",
            field=models.CharField(help_text="档案名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="archive",
            name="id",
            field=models.AutoField(help_text="档案id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="archivecase",
            name="archive",
            field=models.ForeignKey(
                db_column="archive_id",
                help_text="档案id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.archive",
            ),
        ),
        migrations.AlterField(
            model_name="archivecase",
            name="case",
            field=models.ForeignKey(
                db_column="case_id",
                help_text="病例id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.case",
            ),
        ),
        migrations.AlterField(
            model_name="archivecase",
            name="id",
            field=models.AutoField(help_text="自增主键", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="case",
            name="birth_date",
            field=models.DateTimeField(help_text="出生年月日"),
        ),
        migrations.AlterField(
            model_name="case",
            name="blood_type",
            field=models.CharField(
                blank=True, help_text="血型", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_code",
            field=models.CharField(help_text="病例编号", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "女"), (1, "男")], help_text="性别 0-女 1-男"
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="has_transplant_surgery",
            field=models.CharField(
                blank=True,
                default="未填写",
                help_text="是否行移植手术,示例 是(2025-5-27)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="home_address",
            field=models.CharField(
                blank=True, help_text="家庭住址", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.IntegerField(
                help_text="病例id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="identity",
            field=models.ForeignKey(
                db_column="identity_id",
                help_text="身份证号",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.identity",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="inhospital_id",
            field=models.CharField(
                blank=True, help_text="住院号", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="is_in_transplant_queue",
            field=models.CharField(
                blank=True,
                default="未填写",
                help_text="是否存在移植排队",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="main_diagnosis",
            field=models.CharField(
                blank=True, help_text="主要诊断", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(help_text="姓名", max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="opd_id",
            field=models.CharField(
                blank=True, help_text="门诊号", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="联系电话", max_length=36, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="case",
            field=models.ForeignKey(
                db_column="case_id",
                help_text="病例id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.case",
            ),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="check_time",
            field=models.DateTimeField(help_text="检查时间"),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="data_template",
            field=models.ForeignKey(
                db_column="data_template_id",
                help_text="数据模板id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.datatemplate",
            ),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="dictionary",
            field=models.ForeignKey(
                db_column="dictionary_id",
                help_text="词条id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.dictionary",
            ),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="id",
            field=models.AutoField(help_text="自增id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="datatable",
            name="value",
            field=models.CharField(help_text="值", max_length=1024),
        ),
        migrations.AlterField(
            model_name="datatemplate",
            name="category",
            field=models.ForeignKey(
                db_column="category_id",
                help_text="模板分类id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.datatemplatecategory",
            ),
        ),
        migrations.AlterField(
            model_name="datatemplate",
            name="id",
            field=models.AutoField(
                help_text="数据模板id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="datatemplate",
            name="template_code",
            field=models.CharField(help_text="模板编号", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="datatemplate",
            name="template_description",
            field=models.TextField(blank=True, help_text="模板描述", null=True),
        ),
        migrations.AlterField(
            model_name="datatemplate",
            name="template_name",
            field=models.CharField(help_text="模板名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="datatemplatecategory",
            name="id",
            field=models.IntegerField(
                help_text="模板分类id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="datatemplatecategory",
            name="name",
            field=models.CharField(help_text="模板分类名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="datatemplatedictionary",
            name="data_template",
            field=models.ForeignKey(
                db_column="data_template_id",
                help_text="数据模板id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.datatemplate",
            ),
        ),
        migrations.AlterField(
            model_name="datatemplatedictionary",
            name="dictionary",
            field=models.ForeignKey(
                db_column="dictionary_id",
                help_text="词条id",
                on_delete=django.db.models.deletion.CASCADE,
                to="mediCore.dictionary",
            ),
        ),
        migrations.AlterField(
            model_name="datatemplatedictionary",
            name="id",
            field=models.AutoField(help_text="自增id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="data_type",
            field=models.CharField(
                blank=True, help_text="数据类型，如数值类型、文本类型", max_length=128, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="id",
            field=models.AutoField(help_text="词条id", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_apply",
            field=models.CharField(help_text="词条应用", max_length=255),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_belong",
            field=models.CharField(
                blank=True, help_text="从属别名", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_class",
            field=models.CharField(help_text="词条类型", max_length=255),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_code",
            field=models.CharField(help_text="词条编号", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_eng",
            field=models.CharField(
                blank=True, help_text="英文名称", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_name",
            field=models.CharField(db_index=True, help_text="中文名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="word_short",
            field=models.CharField(
                blank=True, help_text="英文缩写", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="birth_date",
            field=models.DateTimeField(help_text="出生年月日"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="gender",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "女"), (1, "男")], help_text="性别 0-女 1-男"
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="identity_id",
            field=models.CharField(
                help_text="身份证号", max_length=255, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="name",
            field=models.CharField(help_text="姓名", max_length=255),
        ),
        migrations.AlterField(
            model_name="images",
            name="case",
            field=models.ForeignKey(
                db_column="case_id",
                help_text="病例id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="mediCore.case",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="data_template",
            field=models.ForeignKey(
                db_column="data_template_id",
                help_text="数据模板id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="mediCore.datatemplate",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="id",
            field=models.AutoField(help_text="自增主键", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="images",
            name="remark",
            field=models.CharField(
                blank=True, help_text="图片备注", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="url",
            field=models.CharField(help_text="图片url", max_length=255),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["identity"], name="idx_identity_id_on_case"),
        ),
    ]
