# Generated by Django 4.2.7 on 2025-05-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediCore", "0004_alter_check_time_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="birth_date",
            field=models.DateField(help_text="出生年月日"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="birth_date",
            field=models.DateField(help_text="出生年月日"),
        ),
    ]
