# Generated by Django 4.2.7 on 2025-05-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediCore", "0005_alter_case_birth_date_alter_identity_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.AutoField(help_text="病例id", primary_key=True, serialize=False),
        ),
    ]
